<?php
use Drupal\context\ContextManager;
use Drupal\Component\Plugin\Context;
use Drupal\context\Plugin\ContextReaction;

function mod_context_reaction_preprocess_html(&$variables){

    if($plugins = \Drupal::service('context.manager')->getActiveReactions('theme_html')) {
        foreach($plugins as $reaction){
            $reaction->execute($variables);
        }
    }

}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function mod_context_reaction_theme_suggestions_page_alter(array &$suggestions, array $variables)
{
    if($plugins = \Drupal::service('context.manager')->getActiveReactions('template_suggestion')) {
        foreach($plugins as $reaction){
            $reaction->execute($suggestions,$variables);
        }
    }
}